#image: danlynn/ember-cli:2.4.3
image: node:5

cache:
  paths:
  - node_modules/

before_script:
  - npm cache clean
  - rm -rf node_modules bower_components dist tmp
  - npm install -g surge gulp-cli bower phantomjs-prebuilt
  - npm install
  - npm set progress=false
  - bower --allow-root install

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm run test

deploy:
  stage: deploy
  script:
    - npm run build
    - npm run deploy
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - npm run build-production
    - npm run deploy-production
  only:
    - production
