image: node:5

cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  untracked: true
  paths:
  - node_modules/

before_script:
  - npm cache clean
  - rm -rf node_modules bower_components dist tmp
  - npm install -g ember-cli surge gulp-cli bower
  - npm install
  - npm set progress=false
  - bower --allow-root install

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm run test

deploy:
  stage: deploy
  script:
    - npm run build
    - npm run deploy
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - npm run build-production
    - npm run deploy-production
  only:
    - production
