image: node:6.2.2

cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  untracked: true
  paths:
  - node_modules/

before_script:
  - npm config set spin false
  # ember-cli dependencies
  - npm install -g bower
  - npm install -g ember-cli
  - npm install -g phantomjs-prebuilt
  # these two are dependencies of our custom build script
  - npm install -g gulp-cli
  - npm install -g surge
  - npm install
  - bower --allow-root install

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - npm run build
    - npm run deploy
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - npm run build-production
    - npm run deploy-production
  only:
    - production
