image: node:5

cache:
  paths:
  - node_modules/

before_script:
  - npm install -g surge gulp-cli bower
  - npm install
  - bower --allow-root install

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm run build
  only:
    - master

build_production:
  stage: build
  script:
    - npm run build-production
  only:
    - production

test:
  stage: test
  script:
    - npm run test

deploy:
  stage: deploy
  script:
    - npm run deploy
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - npm run deploy-production
  only:
    - production
