image: node:5.10

cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  untracked: true
  paths:
  - node_modules/

before_script:
  - npm config set spin false
  - npm install -g ember-cli
  - npm install -g phantomjs-prebuilt
  - npm install -g surge
  - npm install -g gulp-cli
  - npm install -g bower
  - bower --allow-root install
  - npm install

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - npm run build
    - npm run deploy
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - npm run build-production
    - npm run deploy-production
  only:
    - production
